<!DOCTYPE html><html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projeto Final</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="/styles/about.css">
</head>
<body>

<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/register" class="nav-link px-2 text-white">Fala malta!</a></li>       
        <li><a href="/about" class="nav-link px-2 text-secondary">About us</a></li>
        <li><a style="color:goldenrod" href="./login" class="nav-link px-2 ">Login</a></li>
      </ul>

    </div>
  </div>
</header>

 <main class="main">
    <img id="imagem_1" class="mb-4" src="images/Fala_malta_1.png" alt="" >
    <form  class="form-signin"  action="./about"  method="post"> 
         <?php if (isset($message)) : ?>
                 <div class="alert alert-danger">
                     <?= $message ?>
                 </div>
          <?php endif; ?>
          <?php if (isset($info)) : ?>
                 <div id= "alert alert-success" class="alert alert-success">
                       <?= $info ?>
                 </div> 
          <?php endif; ?>
             <h1 id="text-01" class="h3 mb-3 fw-normal">About us!</h1>
             <p id="textAbout">"Fala Malta" is website about social media in the World. If you like to talk to people and make new friends, come with us on this trip! </p>
             <br>
             <p id="footer" >Produção <span id="footer-2">@Rommes</span> | 2021</p> 
     </form>
          
 </main>

</body>
</html>