<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projeto Final</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">

     <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">
     <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" href="/styles/pag_my_profile.css">
</head>
<body>

<header class="p-3 bg-dark text-white">
  <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
           <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
           </a>
           <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a  href="#" class="nav-link px-2 text-white">Fala malta!</a></li>       
              <li><a style="color:goldenrod" href="#" class="nav-link px-2 text-secondary"></a></li>
        
              <li><a style="color:goldenrod" href="/my_profile" class="nav-link px-2 ">My Profile</a></li>
              <li><a style="color:goldenrod" href="/profiles" class="nav-link px-2 ">Profiles</a></li>
              <li><a style="color:gray" href="/public_malta" class="nav-link px-2 ">Public Malta</a></li>
           </ul>
           <div class="text-end"> 
                   <button type="submit" onClick="window.location.replace('./logout')" class="btn btn-outline-light me-2">Logout</button>      
           </div>
      </div>
  </div>
</header>

<main class="main">

   <div id="flex-container">
        <div id="profile" class="col-md-6">
            <strong id="your-profile" class="d-inline-block mb-2 ">Your Profile</strong>
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                 <div class="col p-4 d-flex flex-column position-static">
                        <h3 id="name-profile" class="mb-0"><?= $photoName?>,  @<?= $photoUsername?></h3>                       
                        <div class="mb-1 text">      
                            <input type="text" id="tellAbout" onchange="aboutYou()" style="color:gray" class="card-text mb-auto" value="<?= $aboutUser ?>">
                        </div>
                 </div> 
<?=$allFollowersHTML?>                         
                 <div id="blockImagem" class="col-auto d-none d-lg-block">
                       <form action= "/my_profile" method="post" enctype="multipart/form-data"> 
                             <img id="imagePorfile" src="<?= $photoPath ?>" alt=" <?= $photoName ?>" > 
                             <br><br><br>  
                             <input id="choose-picture" type="file" name="picture" accept=".png,.jpeg,.jpg">
                             <button id="button-upload" type="submit">Upload</button>
                             <!--<div>
                                 <?php // foreach ($images as $image) : ?>  
                                     <img src="<?= $image ?>"  width="200">
                                 <?php // endforeach; ?>   
                             </div> -->
                             <br> 
                       </form>                 
                 </div>   
            </div>
        </div>

        <div id="new-post" class="col">
               <div id="box-new-post" class="card shadow-sm"><br>       
                        <div id="formMessage">
                               <?php if (isset($message)): ?>
                                      <div class="alert alert-info">
                                            <?= $message ?>
                                      </div>
                                <?php endif; ?>
                                <h5 id="create-message">Create message:</h5>
                                <textarea id="writePost"  name="writePost" ></textarea>
                               <input type="date" id="datePost" name="datePost"><br><br> 
                               <input type="button"  id="submitPost" onclick="newMessage()" value="Submit">          
                       </div>
               </div>
        </div>
    </div> 

    <div id="flex-container-2">
      <div id="messagesFriends" class="col-md-6">   
             <strong id="your-profile" class="d-inline-block mb-2 "> Messages your Friends:</strong>
<?=$allPostsHTML?> 
             <ul class="pagination">
                  <li><a href="?pagina=1">First </a></li>
                       <?php if ($pagina >1) : ?>
                          <li class="<?php if($pagina <= 1){ echo 'disabled'; } ?>">
                             <a href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>">Prev </a>
                          </li>
                       <?php endif; ?>
                       <?php if ($pagina < $total_pages) : ?>
                          <li class="<?php if($pagina >= $total_pages){ echo 'disabled'; } ?>">
                              <a href="<?php if($pagina >= $total_pages){ echo '#'; } else { echo "?pagina=".($pagina + 1); } ?>">Next </a>
                         </li>
                       <?php endif; ?>
                  <li><a href="?pagina=<?php echo $total_pages; ?>">Last</a></li>  
             </ul>
      </div>    
    </div>
 
</main>

<script>
               function aboutYou() {
                         let tellAbout = document.getElementById("tellAbout");
                         let xhttp;
                         xhttp = new XMLHttpRequest(); 
                         xhttp.onreadystatechange = function() {
                          if (this.readyState == 4 && this.status == 200) {
                                   tellAbout.style.color ='gold';
                         } else if(this.readyState == 4 && this.status != 200) {
                                   tellAbout.style.color ='red';
                          }  
                         } 
                         xhttp.open("POST","./my_profile", true );
                         xhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                         xhttp.send ('tellAbout=' + encodeURIComponent(tellAbout.value));
                    }                        

                    function newMessage() {
                             let writePost = document.getElementById("writePost");
                             let datePost = document.getElementById("datePost");
                             let xhttp;
                             xhttp = new XMLHttpRequest(); 
                             xhttp.onreadystatechange = function() {
                                 if (this.readyState == 4 && this.status == 200) {
                                        submitPost.style.color ='gold';
                                        datePost.style.color ='gold';
                                        document.getElementById('messagesFriends').innerHTML = '';
                                        let obj = JSON.parse(xhttp.responseText); 
                                        let allPostsHTML = "            <strong id=\"your-profile\" class=\"d-inline-block mb-2 \">Messages your Friends:</strong>\n\n";
                                           for (var i in obj){ 
                                              allPostsHTML += "             <div class=\"row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative\">\n";
                                              allPostsHTML += "                 <div class=\"col p-4 d-flex flex-column position-static\">\n";                       
                                              allPostsHTML += "                     <h3 id=\"name-profile\" class=\"mb-0\">"+ obj[i].name +"</h3>\n";
                                              allPostsHTML += "                     <div class=\"mb-1 text-muted\">"+ obj[i].date +"</div>\n";
                                              allPostsHTML += "                     <p class=\"card-text mb-auto\">"+ obj[i].message +"</p>\n";
                                              allPostsHTML += "                     <a href=\"#\" class=\"stretched-link\"></a>\n";
                                              allPostsHTML += "                 </div>\n";
                                              allPostsHTML += "                 <div class=\"col-auto d-none d-lg-block\"> </div>\n";
                                              allPostsHTML += "             </div>\n"; 
                                            }; 
                                           document.getElementById('messagesFriends').innerHTML = allPostsHTML;           
                                   } else if(this.readyState == 4 && this.status != 200) {
                                                  submitPost.style.color ='red';
                                                  datePost.style.color ='red';
                                        }  
                                   }
                              xhttp.open("POST","./my_profile", true );
                              xhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                              xhttp.send ('writePost=' + encodeURIComponent(writePost.value) + '&datePost=' + encodeURIComponent(datePost.value)); // qual conteudo vou entregar ao Servidor.                              
                    }                        
                                        
</script>
         
</body>
</html>