<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projeto Final</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    
     <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">
     <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" href="/styles/pag_public_malta.css">
</head>
<body>

<header class="p-3 bg-dark text-white">
  <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
           <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
           </a>
           <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a  href="#" class="nav-link px-2 text-white">Fala malta!</a></li>       
              <li><a style="color:goldenrod" href="#" class="nav-link px-2 text-secondary"></a></li>
              <li><a style="color:goldenrod" href="/my_profile" class="nav-link px-2 ">My Profile</a></li>
              <li><a style="color:goldenrod" href="/profiles" class="nav-link px-2 ">Profiles</a></li>
              <li><a style="color:gray" href="/public_malta" class="nav-link px-2 ">Public Malta</a></li>
           </ul>
           <div class="text-end"> 
                   <button type="submit" onClick="window.location.replace('./logout')" class="btn btn-outline-light me-2">Logout</button> 
           </div>
      </div>
  </div>
</header>

<main class="main">
 
   <div id="flex-container">
          <div id="MessagesPublic" class="col-md-6">
                 <strong id="your-profile" class="d-inline-block mb-2 ">Public Malta</strong>
 <?=$allPostsHTML?> 
                 <ul class="pagination">
                     <li><a href="?pagina=1">First </a></li>
                          <?php if ($pagina >1) : ?>
                          <li class="<?php if($pagina <= 1){ echo 'disabled'; } ?>">
                              <a href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>">Prev </a>
                          </li>
                          <?php endif; ?>
                          <?php if ($pagina < $total_pages) : ?>
                          <li class="<?php if($pagina >= $total_pages){ echo 'disabled'; } ?>">
                              <a href="<?php if($pagina >= $total_pages){ echo '#'; } else { echo "?pagina=".($pagina + 1); } ?>">Next </a>
                          </li>
                          <?php endif; ?>
                     <li><a href="?pagina=<?php echo $total_pages; ?>">Last</a></li>  
                 </ul>       
          </div>  
             
          <div id="new-post" class="col">
                <div id="box-new-post" class="card shadow-sm">
                     <br>
                    <form id="formMessage"  action="./public_malta"  method="get"> 
                          <?php if (isset($message)): ?>
                               <div class="alert alert-info">
                                  <?= $message ?>
                               </div>
                          <?php endif; ?>
                          <h5 id="create-message">Search for Message:</h5>
                          <input type="search" id="findPost"  name="searchBox" ><br><br> 
                          <input type="submit" id="submitPost" onclick="searchMessage()" value="Search!">          
                    </form>   
                </div>
          </div>
   </div>
 </main>
         
 <script>
                function searchMessage() {  
                      let findPost = document.getElementById("findPost");
                      let xhttp;
                      xhttp = new XMLHttpRequest(); 
                      xhttp.onreadystatechange = function() {
                          if (this.readyState == 4 && this.status == 200) {
                              findPost.style.color ='gold';
                              document.getElementById('MessagesPublic').innerHTML = xhttp.responseText;    
                          } else if(this.readyState == 4 && this.status != 200) {
                              findPost.style.color ='red';
                          }  
                      }
                      xhttp.open("POST","./public_malta", true );
                      xhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                      xhttp.send ('searchBox=' + encodeURIComponent(findPost.value));                        
                    }      
                                      
</script>

</body>
</html>